using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Collections;

namespace ProtocolCoder
{
    class Generator
    {
        private string output_directory_;
        private Hashtable variables_;
        private Hashtable message_info_from_name_;
        private OutputPrinter Printer;
        private bool IsServerProto;


        public Generator(string OutputDirectory,
                         Hashtable variables,
                         Hashtable MessageInfosFromName, bool ServerProto)
        {
            output_directory_ = OutputDirectory;
            variables_ = variables;
            message_info_from_name_ = MessageInfosFromName;
            IsServerProto = ServerProto;
        }

        /// <summary>
        /// 生成头文件
        /// </summary>
        /// <returns></returns>
        public bool GeneratePythonFile()
        {
            if (!variables_.ContainsKey("FileName"))
            {
                Console.WriteLine("无法找到与输出文件名称相关的信息");
                return false;
            }
            try
            {
                string filename = output_directory_ + variables_["FileName"] + ".py";
                using (StreamWriter sw = new StreamWriter(filename, false, Encoding.UTF8))
                {
                    Printer = new OutputPrinter(sw, '$');
                    Printer.Print("\"\"\"\n********************************************************************\n" +
                                  "**       This head file is generated by program,                   **\n" +
                                  "**            Please do not change it directly.                    **\n" +
                                  "**                   Auther: Fu Yifan                              **\n" +
                                  "********************************************************************/\n\"\"\"\n\n");



                    Printer.Print(variables_, "import common\nimport $InputFile$_pb2\n\n");
                    // 协议分发处理函数
                    Printer.Print(variables_, "class $FactoryName$:\n");
                    Printer.Indent();
                    Printer.Print(variables_, "def Decode(self, MsgID, buf, Size, Proc):\n");
                    Printer.Indent();
                    Printer.Print(variables_, "global $FactoryName$DecodeFuncArray\n");
                    Printer.Print(variables_, "fun = $FactoryName$DecodeFuncArray.get(MsgID)\n");
                    Printer.Print(variables_, "if fun != None:\n");
                    Printer.Indent();
                    Printer.Print(variables_, "fun(buf, Size, Proc)\n");
                    Printer.Outdent();
                    Printer.Outdent();
                    Printer.Outdent();

                    // 生成协议ID
                    int MaxIndex = Convert.ToInt32(variables_["MaxIndex"]);
                    ArrayList tempList = new ArrayList(MaxIndex + 1);
                    for (int i = 0; i < MaxIndex + 1; i++)
                        tempList.Add(null);
                    foreach (DictionaryEntry de in message_info_from_name_)
                    {
                        MessageInfo info = (MessageInfo)de.Value;
                        tempList[info.ID] = info;
                    }
                    for (int i = 0; i < MaxIndex + 1; i++)
                    {
                        if (tempList[i] != null)
                        {
                            MessageInfo info = (MessageInfo)tempList[i];
                            Printer.Print(String.Format("{0} = {1}\n", info.Name, info.ID));
                        }
                    }

                    // 协议处理函数
                    foreach (DictionaryEntry de in message_info_from_name_)
                    {
                        MessageInfo info = (MessageInfo)de.Value;
                        if (info.func == null)
                            continue;

                        Printer.Print(variables_, String.Format("\ndef Decode{0}(buf, size, proc):\n", de.Key));
                        Printer.Indent();

                        if (IsServerProto == info.ByServer)
                        {
                            //info.
                            Printer.Print("try:\n");
                            Printer.Indent();
                            Printer.Print(variables_, String.Format("pkg = $InputFile$_pb2.{0}()\n", info.Type));
                            Printer.Print("pkg.ParseFromString(buf)\n");
                            Printer.Print(String.Format("proc.{0}(pkg);\n", info.func));
                            Printer.Outdent();
                            Printer.Print("except:\n");
                            Printer.Indent();
                            Printer.Print("common.OutputTraceBack()\n");
                            Printer.Outdent();
                        }
                        else
                        {
                            Printer.Print("pass\n");
                        }
                        Printer.Outdent();
                    }

                    // 生成协议到处理函数的映射
                    Printer.Print(variables_, "\n$FactoryName$DecodeFuncArray = {\n");
                    Printer.Indent();
                    foreach (DictionaryEntry de in message_info_from_name_)
                    {
                        MessageInfo info = (MessageInfo)de.Value;
                        if (info.func != null)
                            Printer.Print(String.Format("{0} : Decode{0},\n", de.Key));
                    }
                    Printer.Outdent();
                    Printer.Print("}\n\n");


                    
                    
                }

                return true;
            }
            catch (System.Exception e)
            {
                Console.WriteLine(e.Message);
                return false;
            }
        }

        public bool Run()
        {
            if (!GeneratePythonFile())
                return false;

            //if (!GenerateCPlusPlusFile())
            //    return false;

            return true;
        }
    }
}
